import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "文件系統",
  description: "A web of documents for best team generated by create next app",
};

// async function getDocCategories() {
//   const res = await fetch(
//     `${process.env.NEXT_PUBLIC_STRAPI_URL}/categories?populate=*`
//   );
//   const data = await res.json();
//   return data.data;
// }

// interface docCategories {
//   category: string;
//   content: [];
//   createdAt: string;
//   description: string | null;
//   documentId: string;
//   id: number;
//   publishedAt: string;
//   name: string;
//   updatedAt: string;
//   slug: string;
//   docs: [];
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const docCategories: docCategories[] = await getDocCategories();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-zinc-900`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
